# Generated by Django 4.0.1 on 2024-10-08 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamdislikes',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_dislikes', to='api.dream'),
        ),
        migrations.AddField(
            model_name='dreamdislikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamcommentlikes',
            name='dream_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_comment_likes', to='api.dreamcomment'),
        ),
        migrations.AddField(
            model_name='dreamcommentlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamcommentdislikes',
            name='dream_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_comment_dislikes', to='api.dreamcomment'),
        ),
        migrations.AddField(
            model_name='dreamcommentdislikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_comment_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreamcomment',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_comment', to='api.dream'),
        ),
        migrations.AddField(
            model_name='dreamcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dream',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream', to=settings.AUTH_USER_MODEL),
        ),
    ]
